version: '3'
services:
  SHApi:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    image: SHApi:latest
    ports:
    - "8091:80"
    volumes:
    - ./src:/www/src
    - ./.env.default:/www/.env